- name: Configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable default nodejs version.
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: Enable nodejs version 20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: Install nodejs
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - nodejs
    - mysql

  - name: Install Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: Create expense user 
    ansible.builtin.user:
      name: expense

  - name: create directory 
    ansible.builtin.file:
      path: /app 
      state: directory 

  - name: Download the application code to tmp
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the contents
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app 
      remote_src: yes 

  - name: Install node packages
    community.general.npm:
      path: /app 

  - name: Copy the backend service file
    ansible.builtin.copy:
      src: backend.service 
      dest: /etc/systemd/system/backend.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      state: started
      enabled: yes
      name: backend 

  - name: Import mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.mahedevops.online
      target: /app/schema/backend.sql

  - name: Restart the backend service
    ansible.builtin.service:
      name: backend
      state: restarted

