- name: Configure mysql Server
  hosts: mysql
  become: yes
  tasks:
  - name: Install mysql Server
    ansible.builtin.package:
      name: mysql
      state: absent
  
  # - name: Start and enable mysql service
  #   ansible.builtin.service:
  #     name: mysqld
  #     state: started
  #     enabled: yes
      